# System
apiVersion: backstage.io/v1alpha1
kind: System
metadata: 
  name: One-Login
  description: Swiss Life's Authentication solution, based on Identity Server.
  tags:
    - dotnet
    - ASP.NET
    - Identity Server
  links:
  - url: https://id.a.portals.swisslife.ch/
    title: Developer front-end to One-Login
    icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.    
    backstage.io/source-location: url:https://dev.azure.com/swisslife/IT-Dev-Community/_git/One-Login
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  lifecycle: production
  dependsOn:  
    - One-Login-Identity
    - One-Login-Identity-Classic
    - One-Login-Provisioning
# sub-systems (components)
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-Login-Identity
  description: Swiss Life's Authentication solution for our modern Auth stack.
  tags:
    - dotnet
    - ASP.NET
    - Identity Server
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  dependsOn: 
    - IdentityServer
    - ADConnect
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-Login-Identity-Classic
  description: Swiss Life's Authentication solution for our old Auth stack (ADSVUM).
  tags:
    - dotnet
    - ASP.NET
    - Identity Server
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  dependsOn: 
    - IdentityServer
    - ADConnect  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-Login-Provisioning
  description: Swiss Life's Authentication integration solution for other systems, to synchronize users with C4C, SAP, etc...
  tags:
    - dotnet
    - ASP.NET
    - Identity Server
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  dependsOn: 
    - Provisioning
---
# Components (high level solutions)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: ADConnect
  description: provides integration with Azure Active Directory
  tags:
    - dotnet
    - ASP.NET
    - Identity Server
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  dependsOn: 
    - SwissLife.Configuration
    - SwissLife.Security
    - SwissLife.Health
    - SwissLife.Observability
    - HotChocolate
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: IdentityServer
  description: provides integration with Azure Active Directory
  tags:
    - dotnet
    - ASP.NET
    - Identity Server
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  dependsOn: 
    - SwissLife.Configuration
    - SwissLife.Security
    - SwissLife.Health
    - SwissLife.Observability
    - HotChocolate
    - StrawberryShake
    - Duende.IdentityServer
    - IdOps.IdentityServer
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: Provisioning
  description: Authentication integration solution for other systems, to synchronize users with C4C, SAP, etc...
  tags:
    - dotnet
    - ASP.NET
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  dependsOn: 
    - SwissLife.Configuration
    - SwissLife.Security
    - SwissLife.Health
    - SwissLife.Observability
# external systems/components
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: SwissLife.Configuration
  description: Swiss Life library for handling configuration
  tags:
    - dotnet
    - library
  annotations:
    dev.azure.com/project-repo: F2C/Configuration-Core
spec:
  type: library
  owner: common
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: SwissLife.Security
  description: Swiss Life library for handling security
  tags:
    - dotnet
    - library
  annotations:
    dev.azure.com/project-repo: F2C/Common-Core
spec:
  type: library
  owner: common
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: SwissLife.Health
  description: Swiss Life library for managing and controlling app health
  tags:
    - dotnet
    - library
  annotations:
    dev.azure.com/project-repo: F2C/Common-Core
spec:
  type: library
  owner: common
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: SwissLife.Observability
  description: Swiss Life library for integrating with our Observability platform
  tags:
    - dotnet
    - library
  annotations:
    dev.azure.com/project-repo: F2C/Common-Core
spec:
  type: library
  owner: common
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: HotChocolate
  description: The leading GraphQL library for .NET
  tags:
    - dotnet
    - library
  annotations:
    backstage.io/source-location: url:https://github.com/ChilliCream/graphql-platform
  links:  
    - url: https://chillicream.com/docs/hotchocolate/  
      title: Library Website  
      icon: language  
      type: documentation    
spec:
  type: library
  owner: ChilliCream
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: StrawberryShake
  description: The best client for the leading GraphQL library for .NET
  tags:
    - dotnet
    - library
  annotations:
    backstage.io/source-location: url:https://github.com/ChilliCream/graphql-platform
  links:  
    - url: https://chillicream.com/docs/strawberryshake/  
      title: Library Website  
      icon: language  
      type: documentation    
spec:
  type: library
  owner: ChilliCream
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: Duende.IdentityServer
  description: The most flexible and standards-compliant OpenID Connect and OAuth 2.x framework for ASP.NET Core
  tags:
    - dotnet
    - library
    - ASP.NET Core
  annotations:
    backstage.io/source-location: url:https://github.com/DuendeSoftware/IdentityServer
  links:  
    - url: https://duendesoftware.com/products/identityserver  
      title: Library Website  
      icon: language  
      type: documentation    
spec:
  type: library
  owner: Duende
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: IdOps.IdentityServer
  description: IdOps is a multi-tenant Identity Server resource management platform
  tags:
    - dotnet
    - library
    - ASP.NET Core
  annotations:
    backstage.io/source-location: url:https://github.com/SwissLife-OSS/IdOps
  links:  
    - url: https://github.com/SwissLife-OSS/IdOps  
      title: Library Website  
      icon: language  
      type: documentation    
spec:
  type: library
  owner: SwissLife-OSS
  lifecycle: production
  
# resources (TBD)
  