apiVersion: backstage.io/v1alpha1
kind: System
metadata: 
  name: One-Login
  description: Swiss Life's Authentication solution, based on Identity Server.
  tags:
    - dotnet
    - aspnet
    - identityserver
  links:
  - url: https://id.a.portals.swisslife.ch/
    title: Developer front-end to One-Login
    icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.    
    backstage.io/source-location: url:https://dev.azure.com/swisslife/IT-Dev-Community/_git/One-Login
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  lifecycle: production
  dependsOn:  
    - One-Login-Identity
    - One-Login-Identity-Classic
    - One-Login-Provisioning
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-Login-Identity
  description: Swiss Life's Authentication solution for our modern Auth stack.
  tags:
    - dotnet
    - aspnet
    - identityserver
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  dependsOn: 
    - component:IdentityServer
    - component:ADConnect
    - resource:onelogin-identity-dev
    - resource:OneLogin
    - resource:spc-a-onelogin    
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-Login-Identity-Classic
  description: Swiss Life's Authentication solution for our old Auth stack (ADSVUM).
  tags:
    - dotnet
    - aspnet
    - identityserver
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  dependsOn: 
    - component:IdentityServer
    - component:ADConnect 
    - resource:onelogin-identity-classic-dev   
    - resource:OneLogin-Classic  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-Login-Provisioning
  description: Swiss Life's Authentication integration solution for other systems, to synchronize users with C4C, SAP, etc...
  tags:
    - dotnet
    - aspnet
    - identityserver
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  dependsOn: 
    - component:Provisioning
    - resource:onelogin-provisioning-dev   
    - resource:OneloginProvisioning     
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: ADConnect
  description: provides integration with Azure Active Directory
  tags:
    - dotnet
    - aspnet
    - identityserver
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  dependsOn:  
    - api:ADConnect-api-REST  
    - api:ADConnect-api-GraphQL  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: IdentityServer
  description: provides integration with Azure Active Directory
  tags:
    - dotnet
    - aspnet
    - identityserver
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: Provisioning
  description: Authentication integration solution for other systems, to synchronize users with C4C, SAP, etc...
  tags:
    - dotnet
    - aspnet
  annotations:
    dev.azure.com/project-repo: IT-Dev-Community/One-Login
spec:
  type: service
  owner: common
  system: One-Login
  lifecycle: production
  
# resources (TBD)
---
apiVersion: backstage.io/v1alpha1  
kind: Resource  
metadata:  
  name: onelogin-identity-dev 
  description: OneLogin-Identity API  k8s deployment (development)
  tags:
    - dev
  links:
    - url: https://id.a.portals.swisslife.ch/
      title: App
      icon: dashboard 
  annotations:  
    backstage.io/external-url: https://id.a.portals.swisslife.ch
spec:  
  type: kubernetes-deployment  
  owner: common 
  system: One-Login 
---
apiVersion: backstage.io/v1alpha1  
kind: Resource  
metadata:  
  name: onelogin-identity-classic-dev 
  description: OneLogin-Identity-Classic API k8s deployment (development)
  tags:
    - dev
  links:
    - url: https://id-classic.a.portals.swisslife.ch/
      title: App
      icon: dashboard        
  annotations:  
    backstage.io/external-url: https://id-classic.a.portals.swisslife.ch      
spec:  
  type: kubernetes-deployment  
  owner: common 
  system: One-Login 
---
apiVersion: backstage.io/v1alpha1  
kind: Resource  
metadata:  
  name: onelogin-provisioning-dev 
  description: onelogin-provisioning API k8s deployment (development)
  tags:
    - dev
  links:
    - url: https://onelogin-provisioning.a.portals.swisslife.ch/
      title: App
      icon: dashboard        
spec:  
  type: kubernetes-deployment  
  owner: common 
  system: One-Login  
---
apiVersion: backstage.io/v1alpha1  
kind: Resource  
metadata:  
  name: OneloginProvisioning
  description: OneloginProvisioning MongoDb Database (development)
  tags:
    - dev  
spec:  
  type: database  
  owner: common 
  system: One-Login    
---
apiVersion: backstage.io/v1alpha1  
kind: Resource  
metadata:  
  name: OneLogin-Classic
  description: OneLogin-Classic MongoDb Database (development)
  tags:
    - dev   
spec:  
  type: database  
  owner: common 
  system: One-Login
---
apiVersion: backstage.io/v1alpha1  
kind: Resource  
metadata:  
  name: OneLogin
  description: OneLogin MongoDb Database (development)
  tags:
    - dev   
spec:  
  type: database  
  owner: common 
  system: One-Login   
---
apiVersion: backstage.io/v1alpha1  
kind: Resource  
metadata:  
  name: spc-a-onelogin 
  description: OneLogin-worker Azure Service Bus (development)
  tags:
    - dev   
spec:  
  type: service-bus  
  owner: common 
  system: One-Login    

# AD Connect- rest & graphql // one login access it through it.
# 
# Add new API entities  
---  
apiVersion: backstage.io/v1alpha1  
kind: API  
metadata:  
  name: ADConnect-api-REST  
  description: REST API for ADConnect  
  tags:  
    - dotnet 
    - rest
    - api 
spec:  
  type: openapi  
  lifecycle: production  
  owner: common  
  definition: 'https://raw.githubusercontent.com/joslat/testcatalog/main/catalog/schemas/adsvum-rest-swagger-schema.json' # Replace with the URL or inline OpenAPI specification for the REST API  
  system: One-Login  
---  
apiVersion: backstage.io/v1alpha1  
kind: API  
metadata:  
  name: ADConnect-api-GraphQL  
  description: GraphQL API for ADConnect  
  tags:  
    - dotnet 
    - graphql  
    - api
spec:  
  type: graphql  
  lifecycle: production  
  owner: common  
  definition: 'http://raw.githubusercontent.com/joslat/testcatalog/main/catalog/schemas/adsvum-graphql-schema.graphql' # Replace with the URL or inline GraphQL schema for the GraphQL API 
  system: One-Login  