# System
apiVersion: backstage.io/v1alpha1
kind: System
metadata: 
  name: One
  description: Sample system
  tags:
    - dotnet
    - aspnet
  links:
  - url: https://www.sample.com/
    title: sample
    icon: dashboard
spec:
  type: service
  owner: me
  lifecycle: production
  dependsOn:  
    - One-1
    - One-2
    - One-3
# sub-systems (components)
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-1
  description: sample.
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-2
  description: sample.
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One-Login
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-3
  description: sample..
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-More
  description: sample
  tags:
    - dotnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production